### ISSUE TITLE
53: As a user, I want all the forms in my app to have a user friendly and consistent look.

### ISSUE THREAD

**Issue by tataw-cl** [the-collab-lab/tcl-78-smart-shopping-list#53]
## Description

Style all form in the webapp so they are all consistent and visually easy to look on.

## Acceptance Criteria

- [ ] All forms in components should be differentiable from the rest of the site elements.
- [ ] All form inputs should have a light border outline so they can be easily identified for input when a user lands on a page.
- [ ] Use minimal color related styling for backgrounds since the app background is still pending.

**Comment by eva-lng** [comment]
Closing the issue as it was completed with PR #56
